#!/usr/bin/env bash

CUR_DIR="$(dirname "${BASH_SOURCE[0]}")"

OUTPUT_DIR="${CUR_DIR}/output"
if [ -d "$OUTPUT_DIR" ]; then
	rm -rf "$OUTPUT_DIR"
fi

pipenv install

mkdir "$OUTPUT_DIR"

echo "Copying static directories..."
cp -R "${CUR_DIR}/site/static/css" "$OUTPUT_DIR"
cp -R "${CUR_DIR}/site/static/images" "$OUTPUT_DIR"

cd "${CUR_DIR}" || exit $?
echo "Generating html..."
cd ./site || exit $?
pipenv run python3 generate.py
