#!/usr/bin/env bash

CUR_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${CUR_DIR}" || exit $?

if [[ ! -e "${CUR_DIR}" ]]; then
	echo "ERROR: ${CUR_DIR} is does not exist"
	exit 1
fi

OUTPUT_DIR="${CUR_DIR}/output"
if [[ -d "$OUTPUT_DIR" ]]; then
	rm -rvf "$OUTPUT_DIR"
fi

if [[ "$1" == '-r' ]]; then
	"${CUR_DIR}/remove_null_anilist_sources"
fi

pipenv install

mkdir "$OUTPUT_DIR"

echo "Copying static directories..."
cp -R "${CUR_DIR}/site/static/css" "$OUTPUT_DIR"
cp -R "${CUR_DIR}/site/static/images" "$OUTPUT_DIR"

cd "${CUR_DIR}" || exit $?
echo "Generating html..."
cd ./site || exit $?
pipenv run python3 generate.py
